import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'
import Modal from '../components/Modal'

export default function Home() {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/174/174855.png  " />
      </Head>
  

    {/*Header */}

    <Modal />
    <Header />

    {/* Pages */}

    <Feed />

    {/* modal */}


    </div>
  )
}
